spring:
  application:
    name: yinglibao
  #数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/ylb?useUnicode=true&characterEncoding=UTF-8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
  config:
    import: classpath:conf/jdwx.yml


#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

#redis
server:
  port: 8000
  servlet:
    context-path: /ylb
#salt
secret:
  salt: 8c1ef85a2a5c4a6083491e1a3d85243a